### ISSUE TITLE
Determine Language

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Web-Frontend#2]
We have been given the freedom to choose which language we would prefer to use for this.  We can potentially use the MVC framework in C# which looks as though it may work nicely.  We could also pursue the route of php, which is not as integrated, but seems to be easier to write in at this point.  Either way this should be determined as soon as possible.

**Comment by mgriner** [comment]
I have never used MVC and I am always eager to try something new.  With that said, it is also practical considering the environment we will be setting up and easier for the end user to maintain in the long run.  My vote is for MVC, as long as it is not an impediment.

**Comment by SwipeX** [comment]
We have agreed to use MVC on the front end.
